<?php

namespace App;


use App\BaseModel;
use Illuminate\Database\Eloquent\Builder;


class Post extends BaseModel
{
    //
//    protected $table = 'posts';

//    protected $guarded;  //不可以注入的字段
//
//    protected $fillable=['title','content']; //可以注入的字段

        //关联用户
        public function user()
        {
            return $this->belongsTo('App\User','user_id','id');
        }

        //评论模型
        public function comments()
        {
            return $this->hasMany('App\Comment')->orderBy('created_at','desc');
        }
        //这篇文章对某一个用户是否有赞模型
        public function zan($user_id)
        {
            return $this->hasOne('\App\Zan')->where('user_id',$user_id);
        }
        //所有赞
        public function zans()
        {
            return $this->hasMany('App\Zan');
        }

        public function postTopics()
        {
            return $this->hasMany(\App\PostTopic::class,'post_id','id');
        }

    //不属于某一个专题的文章
    public function scopeTopicNotBy(Builder $query, $topic_id)
    {
        return $query->doesntHave('postTopics', 'and', function($q) use ($topic_id) {
            $q->where("topic_id", $topic_id);
        });
    }

    //属于某一个作者的文章
    public function scopeAuthorBy(Builder $query, $user_id)
    {
        return $query->where('user_id', $user_id);
    }

    /*
     * 可以显示的文章
     */
    public function scopeAviable(Builder $query)
    {
        return $query->whereIn('status', [0, 1]);
    }

    //全局scope的方式
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope("avaiable",function (Builder $builder){
           $builder->whereIn('status',[0,1]);
        });
    }

}
